---
# -*- coding: utf-8 -*-

before_script:
  - source /etc/profile
  - git submodule update --init
  - pyenv local 3.5.1
  - echo "$ACME_POWERDNS_SETTINGS" > .testdata/settings.yml
  - .testdata/run.sh

stages:
  - test

run-test:
  stage: test
  script:
    - make test

# vim: set ts=2 sw=2 tw=2 :
